### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by linmar** [mmamaev/timeboard#18]
In Python 3.10 its not working and shows the following error:

```/usr/local/bin/python3 /xxx
Traceback (most recent call last):
  File "xxx", line 2, in <module>
    import timeboard as tb
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/timeboard/__init__.py", line 7, in <module>
    from .timeboard import Timeboard
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/timeboard/timeboard.py", line 2, in <module>
    from .core import (_Frame, _Timeline, _Schedule,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/timeboard/core.py", line 11, in <module>
    from collections import Iterable, OrderedDict
ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

Process finished with exit code 1
```

This seems to be simmilar to this issue:
https://github.com/noirbizarre/flask-restplus/issues/766

**Comment by mmamaev** [comment]
Fixed in timeboard 0.2.4
